### ISSUE TITLE
Error message text corruption

### ISSUE THREAD

**Issue by kkos** [FairyDevicesRD/libmimiio#4]
examples/mimiio_tumbler/mimiio_tumbler_ex2/のプログラムを動かしていて気付いたのですが、エラーメッセージの一部が文字化けしています。

```
Could not open mimi(R) API service. mimi_open() failed: p�socket connection error no handshake, no connection. (801), retry = 1
mimi connection is successfully opened.
mimi connection is successfully started, decoding starts...
```

調べてみると、const char* mimi_strerror(int errorno)が返している文字列の先頭部分がおかしいようです。

inline std::string strerror(int errorno)の戻り値の型をconst char*に変更し、 mimi_strerror(int errorno)の中をreturn mimiio::strerror(errorno);に変更すれば正しい文字列が表示されるようになりました。
この変更方法が適切かどうかは不明なのでpull requestにはしませんでした。

**Comment by asari-fd** [comment]
ありがとうございます。修正しました。
